### DISCUSSION TITLE
Any known issues with timeline images in 14.0 beta 2 ?

### DISCUSSION THREAD

**Discussion by mayberryjp** [valentinfrlch/ha-llmvision#236] [General]
hi,
Timeline images worked for me in 1.4.0 beta 1, but stopped working in 1.4.0 beta 2. Any known issue?

I read the updated docs, bug reports, etc. 

I tried to remove and re-create the LLM Vision Timeline service in the integration to see if that would fix it - but I haven't triggered any new events yet. My instance is on a remote farm so usually the activity is at night when the animals come out ;)

**Comment by valentinfrlch** [comment]
Does this still happen with the new [release candidate 1](https://github.com/valentinfrlch/ha-llmvision/releases/tag/v1.4.0-rc.1)? The card itself has also received an update.

**Comment by mayberryjp** [comment]
yeah it's even happening on the 1.4.0 GA. i haven't put in any effort to troubleshoot it. i am starting to look at it tonight.

**Comment by mayberryjp** [comment]
This is my initial diagnosis. For 1.4.0 betas and rc1s, i queried events.db and nothing has a filename. It seems I have one event since installing 1.4.0 GA and the filename is different than the filename i tell it to be. 

from events.db


624f2207-aee8-4ac5-87ee-2448f4c7b9af  Cat seen at berry garden                       2025-03-02T20:37:12.043566+09:00  2025-03-02T20:38:18.031444+09:00  Well, look at that—another cat on a covert night mission, presumably called "Boyfriend," stalking the shadows from camera berry garden!                                                                                       /config/www/llmvision/4c234d0c-0.jpg



my automation
```
alias: MOTION | CAT | RECORD EVENT
description: ""
triggers:
  - topic: frigate/events
    trigger: mqtt
conditions:
  - condition: template
    value_template: "{{ trigger.payload_json['after']['label'] == 'cat' }}"
    enabled: true
  - condition: template
    value_template: "{{ trigger.payload_json['type'] == 'new' }}"
actions:
  - action: downloader.download_file
    metadata: {}
    data:
      overwrite: false
      filename: cat-{{trigger.payload_json["after"]["id"]}}.jpg
      url: >-
        http://192.168.50.220:5000/api/events/{{trigger.payload_json["after"]["id"]}}/snapshot.jpg?bbox=0&crop=1
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - action: llmvision.image_analyzer
    metadata: {}
    data:
      remember: true
      include_filename: true
      target_width: 1280
      max_tokens: 50
      model: gpt-4o
      temperature: 1
      generate_title: true
      use_memory: true
      expose_images: true
      provider: 01JM72Z86ZZE8NJY01TS2VKATZ
      message: >-
        Summarize what is happening in the camera feed (one sentence max). Do
        not describe the scene! If there is an animal in the photo please
        describe the size, color and type of animal. If there is not an animal
        in the photo then simply state that no animal was detected. Make it
        humorous and condescending. Please also mention that the image is from
        camera {{trigger.payload_json["after"]["camera"]}}. Do you recognize an
        animal in this image? It is critical you identify the animal based on
        the reference images shown to you. if you do not know what this animals
        name is then please say it.
      image_file: /config/previews/cat-{{trigger.payload_json["after"]["id"]}}.jpg
    response_variable: llmvision_response
  - action: telegram_bot.send_message
    metadata: {}
    data:
      message: "{{ llmvision_response.response_text }}"
mode: single
```
