### DISCUSSION TITLE
Avoid notification if response is "No activity observed"

### DISCUSSION THREAD

**Discussion by superkekko** [valentinfrlch/ha-llmvision#302] [Ideas]
@valentinfrlch do you think it will be possibile to only avoid notification if the response il "No activity observed"? I use the motion sensor in the cameras but, since they are looking in a garden outside the leaf movement trigger the motion for no reason. I care to have the identification in the timeline but I don't want the notification.

**Comment by tabascoz** [comment]
would be nice to have it + 1 :) unsure if it is possible to use the run conditions, but i am afraid not possible the way the automation works now.

**Comment by valentinfrlch** [comment]
For now you can enable `important`. This doesn't do exactly what you're asking. As the name suggests, it will only send notifications for "important" events. You could customize the prompt for the `important` feature. You'll have to take control of the blueprint to do that.

**Idea**: Add an optional filter (check `"no activity observed" in response.title`) and only send the notification if true.

**Comment by superkekko** [comment]
I've figured out how to do that. I've done an automation and using a specific response if no mevement is detected I've puted a "if" block as follow

![immagine](https://github.com/user-attachments/assets/2298439f-826a-4ebd-a518-2eb004cf6200)

**Reply by superkekko** [reply]
Here the complete YAML if someone need it

```
alias: Motion record esterno ovest
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.motion_camera_esterno_ovest
    to: Detected
    from: None
conditions: []
actions:
  - variables:
      filename: >-
        /media/recordings/esterno_ovest/{{now().strftime("%Y%m%d")}}/{{now().strftime("%Y%m%d-%H%M%S")}}.mp4
  - action: camera.record
    metadata: {}
    data:
      duration: 60
      filename: "{{filename}}"
    target:
      device_id: 64a2639e67f6b15c314b2c1c525624a3
  - delay:
      hours: 0
      minutes: 1
      seconds: 1
      milliseconds: 0
  - action: llmvision.video_analyzer
    metadata: {}
    data:
      remember: false
      use_memory: false
      include_filename: false
      target_width: 1280
      max_tokens: 100
      temperature: 0.2
      generate_title: true
      expose_images: true
      provider: 01JQRND0QEAKHP6TRTQBCT3SN9
      model: gemini-2.0-flash
      message: >-
        Summarize the events in this video. Focus only on moving subjects such
        as people, vehicles, and other active elements. Ignore static objects
        and scenery. Provide a clear and concise account of movements and
        interactions. Do not mention or imply the existence of video. Present
        the information as if directly observing the events. If no movement is
        detected, respond with: 'No activity observed.'
      max_frames: 5
      video_file: "{{filename}}"
    response_variable: response
  - if:
      - condition: template
        value_template: "{{ response.response_text != \"No activity observed.\" }}"
    then:
      - action: notify.mobile_app_pixel_7_pro
        metadata: {}
        data:
          title: Esterno ovest {{response.title}}
          message: "{{response.response_text}}"
          data:
            image: "{{response.key_frame.replace('/config/www/','/local/') }}"
            actions:
              - action: URI
                title: Apri Home assistant
                uri: /dashboard-survelliance
      - action: notify.persistent_notification
        metadata: {}
        data:
          title: Esterno ovest {{response.title}}
          message: "{{response.response_text}}"
      - action: llmvision.remember
        metadata: {}
        data:
          image_path: "{{response.key_frame.replace('/config/www/','/local/') }}"
          summary: "{{response.response_text}}"
          title: "{{response.title}}"
          camera_entity: camera.esterno_ovest
mode: single
```
