### DISCUSSION TITLE
Add Telegram Notifications to Blueprint

### DISCUSSION THREAD

**Discussion by Menz01** [valentinfrlch/ha-llmvision#329] [Ideas]
I would like to request a modification to the blueprint to allow images and notifications to be sent via a telegram notification.  i have the current blueprint setup to send to my android Pixel phone and the message gets truncated and i cant get the whole message

**Comment by hughc-hub** [comment]
Something like this could do the trick for you:
```
alias: AI Gemini-Analisis (using Telegram)
description: ""
triggers:
  - type: value
    device_id: your camera device
    entity_id: your person count entity
    domain: sensor
    trigger: device
    above: 0
conditions: []
actions:
  - action: llmvision.image_analyzer
    metadata: {}
    data:
      remember: true
      use_memory: true
      include_filename: true
      target_width: 1280
      max_tokens: 100
      generate_title: false
      expose_images: false
      provider: Select your provider
      image_entity:
        - camera.garden
      message: |2-
            message: >-
					YOUR PROMPT
    response_variable: geminiresponse
  - action: telegram_bot.send_photo
    metadata: {}
    data:
      file: "{{ geminiresponse.key_frame }}"
      caption: |-
        *{{ geminiresponse.title.strip() }}*
        {{ geminiresponse.response_text }}
      config_entry_id: your telegram entry id
    enabled: true
mode: single
```
