### DISCUSSION TITLE
Can't get a trigger

### DISCUSSION THREAD

**Discussion by cliffburdick** [valentinfrlch/ha-llmvision#331] [Q&A]
Hi all, first off this is a really promising library and I'm looking forward to using it more. I have a frigate setup that when I go into developer options->actions I can successfully make an LLM vision Image Analyzer trigger with ollama on my remote server and setting the entity to "Porch Person" (my camera is called Porch. When I test the action it successfully describes the scene. 

The problem is I'm trying to add an automation for it, but something isn't quite working when I use the blueprint. Under run conditions I have "Current Porch Person Active Count Value" and have it greater than 0. I can see this entity is increasing when I look at the counter in HA. I have the camera entity set to Porch, and the trigger state is set to "recording". Despite this, it shows that it's never been triggered even when I walk in front of the camera and see the counter increasing. 

Does anyone know what can be wrong? I think the piece I'm not connecting is how the blueprint is getting the snapshot/clips from frigate.

**Comment by valentinfrlch** [comment]
Hi, can you share your Blueprint configuration? 
LLM Vision doesn't fetch the clips from Frigate, but instead streams the cameras once the blueprint has been triggered. Camera feeds are accessed through the Home Assistant Frigate integration.

**Comment by cliffburdick** [comment]
Hi @valentinfrlch , thanks for the response. This is what I have:

```
alias: Porch Test
description: ""
use_blueprint:
  path: valentinfrlch/event_summary.yaml
  input:
    camera_entities:
      - camera.porch
    motion_sensors:
      - binary_sensor.porch_and_lawn_person_occupancy
    notify_device:
      - bb1fe386b0f67cccb57429bc0e8d6983
    model: gemma3
    provider: 01JTF9V7Q2FJYKND7TY4RWWW4K
```
