### DISCUSSION TITLE
Bypass notification when No activity observed

### DISCUSSION THREAD

**Discussion by marc3k18** [valentinfrlch/ha-llmvision#340] [Q&A]
Will be great to Bypass notification and timeline when No activity observed

**Comment by valentinfrlch** [comment]
The blueprint has been updated to include `condition_notify`. I believe you can use `{{camera_entity}}` to reference the camera that triggered the blueprint.

**Comment by tabascoz** [comment]
Hi @valentinfrlch  in 1.4.2 i used to have the filter defined (manually) below: 

```
      - if:
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ response.response_text !=  \"No activity observed.\" }}"
```

But since 1.4.3 i tried to use the same as notification condition but i keep receiving messages with description "No activity observed." May i ask you any clue of how should it be coded to avoid receiving such messages in 1.4.3? Thanks
