### DISCUSSION TITLE
Missing Screenshot?

### DISCUSSION THREAD

**Discussion by cliffburdick** [valentinfrlch/ha-llmvision#373] [Q&A]
Hi, I have the blueprint configured where it's consuming events from frigate when a person is on our porch. This was working well on an old blueprint. I had to wipe HA and start over, but with the new config even though I get an alert when a person is there, there are no screenshots in the notifications. The closest thing I can find is the file path, but it seems that's set to the default:
![image](https://github.com/user-attachments/assets/2c7e63e6-8a0d-4cfd-8340-3fa29b23742c)

Is there somewhere else to debug this?

YAML:
```
alias: Person porch
description: ""
use_blueprint:
  path: valentinfrlch/event_summary.yaml
  input:
    camera_entities:
      - camera.porch
    motion_sensors:
      - binary_sensor.porch_person_occupancy
    message: >-
      Describe only the person in the image and nothing in the scene. describe
      what they are wearing and what they look like.
    provider: 01JW4J21Z6EJGKVRRXDRMNGYW7
    model: gemma3
    notify_device:
      - 376356d9f91569c9a4c48f492025f0cf
```

I do get this error:
```
homeassistant  | 2025-06-03 13:50:21.988 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'camera' is undefined when rendering '{{ camera }} Snapshot'
homeassistant  | 2025-06-03 13:50:21.991 ERROR (MainThread) [homeassistant.components.automation.person_porch] Person porch: If at step 3: If at step 1: If at step 1: Choose at step 1: choice 1: Choose at step 1: choice 1: Error executing script. Error for call_service at pos 1: Cannot write `Media Folder - Secured`, no access to path; `allowlist_external_dirs` may need to be adjusted in `configuration.yaml`
homeassistant  | 2025-06-03 13:50:21.991 ERROR (MainThread) [homeassistant.components.automation.person_porch] Person porch: If at step 3: If at step 1: If at step 1: Choose at step 1: choice 1: Error executing script. Error for choose at pos 1: Cannot write `Media Folder - Secured`, no access to path; `allowlist_external_dirs` may need to be adjusted in `configuration.yaml`
homeassistant  | 2025-06-03 13:50:21.992 ERROR (MainThread) [homeassistant.components.automation.person_porch] Person porch: If at step 3: If at step 1: If at step 1: Error executing script. Error for choose at pos 1: Cannot write `Media Folder - Secured`, no access to path; `allowlist_external_dirs` may need to be adjusted in `configuration.yaml`
homeassistant  | 2025-06-03 13:50:21.992 ERROR (MainThread) [homeassistant.components.automation.person_porch] Person porch: If at step 3: If at step 1: Error executing script. Error for if at pos 1: Cannot write `Media Folder - Secured`, no access to path; `allowlist_external_dirs` may need to be adjusted in `configuration.yaml`
homeassistant  | 2025-06-03 13:50:21.992 ERROR (MainThread) [homeassistant.components.automation.person_porch] Person porch: If at step 3: Error executing script. Error for if at pos 1: Cannot write `Media Folder - Secured`, no access to path; `allowlist_external_dirs` may need to be adjusted in `configuration.yaml`
homeassistant  | 2025-06-03 13:50:21.992 ERROR (MainThread) [homeassistant.components.automation.person_porch] Person porch: Error executing script. Error for if at pos 3: Cannot write `Media Folder - Secured`, no access to path; `allowlist_external_dirs` may need to be adjusted in `configuration.yaml`
homeassistant  | 2025-06-03 13:50:21.992 ERROR (MainThread) [homeassistant.components.automation.person_porch] Error while executing automation automation.person_porch: Cannot write `Media Folder - Secured`, no access to path; `allowlist_external_dirs` may need to be adjusted in `configuration.yaml`
```
