### ISSUE TITLE
Support from images that use the homeassistant /api end point?

### ISSUE THREAD

**Issue by npike** [valentinfrlch/ha-llmvision#111]
**Is your feature request related to a problem? Please describe.**
I would like to feed Nest doorbell event images to your integration, but they are mostly easily available via the homeassistant /api end points (instead of file paths).

i.e.  
api/nest/event_media/[nest device id]/[nest event id]/thumbnail

**Describe the solution you'd like**
"Image File" field could support local API urls like /api or a new field is exposed in the Action just for this.

**Describe alternatives you've considered**
I tried using the "api/" URL in the existing "Image File" field.

Thanks in advance!

**Comment by valentinfrlch** [comment]
I don't have any nest cameras so I am unfamiliar with them. Doesn't the Google Nest integrations provide camera entities? If so you can use them directly in the `image_entity` field.

**Comment by johndeu** [comment]
Second request for this feature to support Nest cameras - or provide guidance on how to use them with LLM Vision. 

Nest does provide camera entities, but it provides the events from the cameras different than most. 
Happy to test if you have an idea on how to integrate this. 

For example a front door doorbell from Nest creates a camera.front_door entity and also creates two events.
event.front_door_motion and event.front_door_chime 

See the documentation from Google Nest integration here - [Nest integration events](https://www.home-assistant.io/integrations/nest#event )

The images are sent as attachments from the events.  [Nest integration Media Attachments]( https://www.home-assistant.io/integrations/nest#media-attachments)

Here is an example automation for a Nest camera detecting a person at the front door.

alias: "Person detected front door "
description: ""
triggers:
  - device_id: 56bb648a467c7b18f3d57fecXXXXXXXX
    domain: nest
    type: camera_person
    trigger: device
  - device_id: 56bb648a467c7b18f3d57fecXXXXXXX
    domain: nest
    type: doorbell_chime
    trigger: device
conditions: []
actions:
  - metadata: {}
    data:
      title: Front Door Person Detected
      message: Person detected at front door
      data:
        image: |
          {{ trigger.event.data.attachment.image}}
        video: |
          {{ trigger.event.data.attachment.video }}
    action: notify.persistent_notification
  - action: notify.mobile_app_iOS_device_1
    metadata: {}
    data:
      message: Person detected at front door
      title: Person at front door
      data:
        image: |
          {{ trigger.event.data.attachment.image}}
        video: |
          {{ trigger.event.data.attachment.video }}
mode: single


The logs from Nest in the storage folder look like this and show the SDM events. This one is motion, but there can be "motion", "person", "sound", "chime"

![image](https://github.com/user-attachments/assets/18372eaa-61b3-4d2e-ae3f-3858cfcaf00d)


   {
        "event_session_id": "AVPHwEvZgIPd2uZ-sac_nSJZpPFyoywBK1-mGZpK7rcod5yEimlnw-qCzCwg8mNx_0ibjHGHlut_OPOshB_PxKKJ5MZqWA",
        "events": {
          "sdm.devices.events.CameraMotion.Motion": {
            "event_type": "sdm.devices.events.CameraMotion.Motion",
            "event_data": {
              "event_session_id": "AVPHwEvZgIPd2uZ-sac_nSJZpPFyoywBK1-mGZpK7rcod5yEimlnw-qCzCwg8mNx_0ibjHGHlut_OPOshB_PxKKJ5MZqWA",
              "timestamp": "2024-12-07T18:15:02.128000+00:00",
              "event_id": "CiUA2vuxrxdLL0PWf1uw8QVfsPzRW-Ss1uUgwwlALjm7HNUsybb9EowBAGsO4kFuKGjzZpHOash4eK0tUud9W-AEc1M36RhHAYcjuRJHfaz2BfYoGtE0g7wCIrwuvRBwt7Wl9dXWD936_xmEWvG9sP0QKmODbz3GhSNeohey-K-45kKZIFuU1K2Ti3Ybi6Hq8DMFI4XrUp-Lmjo3rEJsnbNORuf4H11QnS6K8gPWeN4lFAmqQEQ",
              "event_image_type": "image/jpeg",
              "zones": []
            },
            "timestamp": "2024-12-07T18:15:02.128000+00:00",
            "event_image_type": "image/jpeg"
          }
        },
        "media_key": null,
        "event_media_keys": {
          "CiUA2vuxrxdLL0PWf1uw8QVfsPzRW-Ss1uUgwwlALjm7HNUsybb9EowBAGsO4kFuKGjzZpHOash4eK0tUud9W-AEc1M36RhHAYcjuRJHfaz2BfYoGtE0g7wCIrwuvRBwt7Wl9dXWD936_xmEWvG9sP0QKmODbz3GhSNeohey-K-45kKZIFuU1K2Ti3Ybi6Hq8DMFI4XrUp-Lmjo3rEJsnbNORuf4H11QnS6K8gPWeN4lFAmqQEQ": "6374e0b4c750b4105bd9de6a8adcd965/1733595302-camera_motion.jpg"
        },
        "thumbnail_media_key": null,
        "pending_event_keys": []
      }
    ]
  }

**Comment by npike** [comment]
For what its worth, I got it to work "sort of" using this path for image_file (building up the path to where the nest integration stores its media based on the trigger device id and timestamp).  Seems to work well enough for now :). Replace `person` with `motion` or `chime` (haven't tested `chime`, so YMMV).

```
/config/nest/event_media/{{ trigger.event.data.device_id }}/{{
            as_timestamp(trigger.event.data.timestamp) | int }}-camera_person.jpg
```

The complete action call looks like this:

```
data:
  provider: Google
  target_width: 1280
  max_tokens: 100
  temperature: 0.5
  message: >-
    you are jarvis from iron-man, with humour identify what is happening in this
    image. use less than 75 characters. do not tell me this is a response that
    is under the character limit. 
    dont mention the Christmas tree. dont mention the porch. dont mention the
    location of the person at all. 
  image_file: |
    /config/nest/event_media/{{ trigger.event.data.device_id }}/{{
            as_timestamp(trigger.event.data.timestamp) | int }}-camera_person.jpg
response_variable: response
action: llmvision.image_analyzer
enabled: true

```

**Comment by johndeu** [comment]
@npike  - I was able to get the basics of that triggering in the Actions panel of the Developer tools as well, but the template "trigger" part was not working there of course.  How did you get this to actually trigger from the motion sensor on the camera?  That's where I am stuck.

I ended up just hard coding a path to see if it worked in the developer tools.

action: llmvision.image_analyzer
data:
  provider: 01JE9KX8DNAM2T2HPEX0RKP71W
  mode: camera
  model: gemini-1.5-flash
  message: Describe the image concisely and accurate. Respond with only the description. Focus on the people and what they look like. Count cars visible. Identify any logos on trucks or vehicles
  include_filename: false
  remember: false
  image_file:  /config/nest/event_media/56bb648a467c7b18f3d57fec5b30f9a8/1732386439-camera_person.jpg
  target_width: 1280
  detail: low
  max_tokens: 100
  temperature: 0.2

**Comment by johndeu** [comment]
Got it working pretty well now with just a custom automation. 
Hopefully this will help someone else using the NEST cameras or doorbells.  I tested it with my Nest v1 Doorbell and also a Nest indoor camera. I'll check outdoor battery cameras next, but I don't think they support event media.

``` yaml
alias: Nest Camera Motion Detected LLM
description: ""
triggers:
  - device_id: 6374e0b4c750b4105bd9xxxxxxxxxxxxxx
    domain: nest
    type: camera_person
    trigger: device
conditions: []
actions:
  - action: llmvision.image_analyzer
    response_variable: response
    data:
      provider: Google
      mode: camera
      model: gemini-1.5-flash
      message: >-
        Identify this as the front door camera. Describe the image concisely and
        accurate. Respond with only the description. Focus on the people and
        what they look like. Count cars visible. Identify any logos on trucks or
        vehicles. Describe the weather conditions.
      include_filename: false
      remember: true
      image_file: |
        /config/nest/event_media/{{ trigger.event.data.device_id }}/{{
                as_timestamp(trigger.event.data.timestamp) | int }}-camera_person.jpg
      target_width: 1280
      detail: low
      max_tokens: 150
      temperature: 0.7
  - variables:
      llm_output: "{{ response.response_text }}"
  - action: notify.persistent_notification
    data:
      title: Person detected
      message: |
        Front door person detected: {{ llm_output  }}
      data:
        image: |
          /config/nest/event_media/{{ trigger.event.data.device_id }}/{{
                as_timestamp(trigger.event.data.timestamp) | int }}-camera_person.jpg
  - action: notify.mobile_app_my_iOS_device
    metadata: {}
    data:
      title: Person detected
      message: |
        Front door person detected: {{ llm_output  }}
      data:
        image: |
          /config/nest/event_media/{{ trigger.event.data.device_id }}/{{
                as_timestamp(trigger.event.data.timestamp) | int }}-camera_person.jpg
mode: single
```
