### ISSUE TITLE
Failed to perform the action llmvision.stream_analyzer. No image input provided

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [valentinfrlch/ha-llmvision#113]
First of all, thank you for creating this system! I'm trying it for the first time and got stuck:

### Bug Description

I ran action `LLM Vision: Stream Analyzer` with my Generic Camera which has a stream, and it says no image input provided. I'm clueless. All my cameras are ONVIF with RTSP streams.

Camera entity I tried to use:
![image](https://github.com/user-attachments/assets/7c154098-7b33-4e07-8b98-8e08769ceefe)

**Version**: v1.3.1

### Service Call

```yaml
action: llmvision.stream_analyzer
data:
  duration: 5
  max_frames: 3
  include_filename: false
  target_width: 1280
  detail: low
  max_tokens: 100
  temperature: 0.2
  provider: 01JE8YYXHR04KV5JT4W3DSED7K
  message: Describe the image in one short sentence
  image_entity:
    - camera.192_168_68_111
```

### Additional Information

From my understanding, the camera's image(s) aren't being fetched successfully.
