### ISSUE TITLE
models/gpt-4o-mini is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.

### ISSUE THREAD

**Issue by ward0** [valentinfrlch/ha-llmvision#114]
### Bug Description

![image](https://github.com/user-attachments/assets/a1bd9990-665c-4a75-ba01-6377b17ae47a)

**1.3.1**: 

### Service Call

```yaml
id: '1733408125098'
alias: camera buiten AI
description: ''
use_blueprint:
  path: valentinfrlch/event_summary.yaml
  input:
    mode: Camera
    notify_device:
      - 0415a989155b9f3c8cb9a7a38c623b16
    camera_entities:
      - camera.buiten_fluent
    preview_mode: Snapshot
    cooldown: 5
    provider: 01JDYQD401EYV2TTVFJW6WTTDY
    message: Describe if the gate or open or closed (one sentence max).
    motion_sensors:
      - binary_sensor.buiten_motion
      - binary_sensor.buiten_person
```

### Logs

```
Logger: homeassistant.components.automation.camera_buiten_ai
Source: helpers/script.py:2032
integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 3:24:59 PM (2 occurrences)
Last logged: 3:24:59 PM

camera buiten AI: Analyze event: choice 2: Error executing script. Error for call_service at pos 1: models/gpt-4o-mini is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
camera buiten AI: Error executing script. Error for choose at pos 4: models/gpt-4o-mini is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.

Logger: homeassistant.components.automation.camera_buiten_ai
Source: components/automation/__init__.py:764
integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 3:24:59 PM (1 occurrences)
Last logged: 3:24:59 PM

Error while executing automation automation.camera_buiten_ai: models/gpt-4o-mini is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods.
```
