### ISSUE TITLE
AI Motion description (automation.ai_motion_description) has an unknown action

### ISSUE THREAD

**Issue by rappazzo** [valentinfrlch/ha-llmvision#121]
AI Motion description (automation.ai_motion_description) has an unknown action

### Bug Description
I setup the blueprint to try to notify on my cell, and it is giving me this error whenever it triggers

> The automation "AI Motion description" (automation.ai_motion_description) has an unknown action: notify.mobile_app_mikes_cell_receiver_2023.

I'm only able to select "Mike's Cell Receiver 2023" from the notify devices drop down

**Version**: 1.3.1

### Service Call

```yaml
alias: AI Motion description
description: ""
use_blueprint:
  path: valentinfrlch/event_summary.yaml
  input:
    mode: Frigate
    important: true
    remember: true
    notify_device:
      - 8f68633393b61575ad9f63a8dcc30103
    camera_entities:
      - camera.front_flood
    preview_mode: Snapshot
    provider: 01JDSKTAAJ2N4BD93K25XH7Q6K
    temperature: 0.6
    tap_navigate: /ccab4aaf_frigate-proxy/ingress
    cooldown: 0
    model: gemini-1.5-flash-latest
```

### Logs
From the general Logs (not debug enabled):
```
AI Motion description: Error executing script. Service not found for choose at pos 3: Action notify.mobile_app_mikes_cell_receiver_2023 not found
AI Motion description: Already running
AI Motion description: Choose at step 3: choice 1: Send instant notification to notify devices: Error executing script. Service not found for call_service at pos 1: Action notify.mobile_app_none not found
AI Motion description: Choose at step 3: choice 1: Error executing script. Service not found for repeat at pos 1: Action notify.mobile_app_none not found
AI Motion description: Error executing script. Service not found for choose at pos 3: Action notify.mobile_app_none not found
```

### Additional context
I tried to change the `notify_device` to the value that I use in my other automations (`mobile_app_mike_s_cell_receiver_2023`), but that didn't seem to work either.  Also, when I returned to edit the blueprint, it blanked out the drop down when I tried that value.
