### ISSUE TITLE
Similarity Score: Input array dimensions mismatch

### ISSUE THREAD

**Issue by codyderrick** [valentinfrlch/ha-llmvision#142]
### Bug Description
I get the exception using a Reolink RLC-840WA camera and the gemini-1.5-pro model with the HA LLM Vision blueprint.

**Version**: 1.3.1

### Service Call

```yaml
action: llmvision.video_analyzer
data:
  max_frames: 3
  include_filename: false
  target_width: 1280 
  detail: low
  max_tokens: 100
  temperature: 0.2
  provider: 01JECGS6MVT1PTGBHX9S5T4JBJ
  model: gemini-1.5-pro
  message: >-
    If there is a person, describe what they're doing and
    what they look like. If they look like a courier mention that! If nothing is
    happening, say so.
  event_id: 1734548561.083979-evyrs5
```

### Logs

```
Logger: homeassistant.components.automation.llm_vision_patio
Source: components/automation/__init__.py:764
integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 10:46:07 AM (1 occurrences)
Last logged: 10:46:07 AM

Error while executing automation automation.llm_vision_patio: Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4915200 and the array at index 1 has size 8294400

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:820
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 10:38:47 AM (4 occurrences)
Last logged: 10:46:48 AM

[139803960819376] Error: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4915200 and the array at index 1 has size 8294400
```

### Additional context
The image and stream analyzers both produce results for this camera.
