### ISSUE TITLE
UnboundLocalError: cannot access local variable 'new_value' where it is not associated with a value

### ISSUE THREAD

**Issue by Inrego** [valentinfrlch/ha-llmvision#151]
### Bug Description
Trying to use data analyzer to a boolean

**1.3.5**: 

### Service Call

```yaml
action: llmvision.data_analyzer
data:
  message: Is the gate open? Respond with true/false/unknown
  include_filename: false
  target_width: 1280
  max_tokens: 5
  temperature: 0.1
  provider: 01JGM8BWRQPSSP3SY264G0ZWCE
  sensor_entity: input_boolean.port_2_aben
  image_entity:
    - camera.port_2
```

### Additional context
I tried the same prompt in image analyzer, and it responds with "false".
