### ISSUE TITLE
Error: Unsupported sensor entity type

### ISSUE THREAD

**Issue by herb0072** [valentinfrlch/ha-llmvision#153]
### Bug Description
Text input helper no longer working with this action.

**Version**: 1.3.5

### Service Call
```yaml
actions:
  - action: llmvision.data_analyzer
    metadata: {}
    data:
      message: Is the grey trash can by the garage door or the curb?
      include_filename: false
      target_width: 1280
      max_tokens: 5
      temperature: 0.1
      provider: ***
      model: gemini-1.5-flash
      sensor_entity: input_text.garbage_bin
      image_entity:
        - camera.driveway
```

### Logs
```
Logger: homeassistant.components.automation.new_automation_4
Source: components/automation/__init__.py:764
integration: Automation (documentation, issues)
First occurred: 8:44:54 PM (10 occurrences)
Last logged: 9:28:54 PM

Error while executing automation automation.new_automation_4: Unsupported sensor entity type
```

### Additional context
Was text input type helpers removed on purpose? I see the IF blocks trying to be specific about things to filter correctly, but I will just take whatever text the LLM gives me here.
