### ISSUE TITLE
 Formatting response_text

### ISSUE THREAD

**Issue by d1nc174** [valentinfrlch/ha-llmvision#154]
### Bug Description
The response_text output from the LLM Vision Analyzer action when using Gemini is currently formatted as a block scalar (|) in YAML. For example:

response_text: |
  Nothing is happening in the camera feed.

**Version**: 1.3.5

### Service Call

```yaml
action: llmvision.image_analyzer
data:
  include_filename: false
  target_width: 1280
  max_tokens: 100
  temperature: 0.2
  generate_title: false
  expose_images: false
  expose_images_persist: false
  provider: 01JBQCY1EBQ6VMFMAPJNSSGYYZ # Google Gemini
  message: |-
    Summarize what's happening in the camera feed (one sentence max). Don't
            describe the scene! If there is a person, describe what they're doing
            and what they look like. If they look like a courier mention that! If
            nothing is happening, say so.
  image_entity:
    - camera.reolink_trackmix_wifi_fluent_lens_1
```

### Logs

```
Paste relevant logs here
```

### Additional context
This formatting introduces unnecessary newlines and indentation in the string, which creates issues when using the value in Home Assistant scripts and automations. Specifically:

Media Player TTS Problem: When attempting to pass response_text as part of a media_content_id (e.g., for TTS via media_player.play_media), the multi-line format prevents the response from being interpreted correctly.

Additional Preprocessing Required: Users must apply Jinja2 filters like replace("\n", "") and trim to remove the newlines and format the text properly for use in scripts. This adds unnecessary complexity for users and makes automations more error-prone.
