### ISSUE TITLE
cannot access local variable 'new_value' where it is not associated with a value

### ISSUE THREAD

**Issue by Elbredde** [valentinfrlch/ha-llmvision#156]
### Bug Description

Since update LLM Vision causes the shown mistake, I tried to produce logs but immediately. The camera is a Reolink Altas PT Ultra and teh automation anaylses if there cars, delivery service, persons or animals involved trigger the input_boolean, the automation worked fine for about 2 weeks and I didn't change it

**1.3.6**: stepped back to 1.3.1 which solved the problem 

### Service Call

```yaml
<actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Fahrzeug
        sequence:
          - action: llmvision.data_analyzer
            metadata: {}
            data:
              message: Ist das Fahrzeug ein Paketdienst?
              include_filename: false
              target_width: 1280
              detail: high
              max_tokens: 5
              temperature: 0.1
              provider: OpenAI
              sensor_entity: input_boolean.paketdienst
              image_entity:
                - camera.reolink_veranda_schnappschusse_klar
                - image.hof_event_image
          - action: llmvision.data_analyzer
            metadata: {}
            data:
              message: Ist ein Fahrzeug zu sehen?
              include_filename: false
              target_width: 1280
              detail: high
              max_tokens: 5
              temperature: 0.1
              provider: OPENAI
              sensor_entity: input_boolean.fahrzeug
              image_entity:
                - camera.reolink_veranda_schnappschusse_klar
                - image.hof_event_image
```>

### Logs
<!-- Check README to enable debugging -->
```
Paste relevant logs here
Gestoppt, weil am 3. Januar 2025 um 12:10:05 ein Fehler aufgetreten ist (Laufzeit: 8.14 Sekunden)
Transiten: Stoppes, on 3rd of Jan 2025 at 12.10.05 an error occurred (runtime 8.14 seconds)

cannot access local variable 'new_value' where it is not associated with a value

### Additional context
Since the update the automation didn't  run anymore stepping back to Version 1.3.1 solved the problem, it's now working again without the updates
