### ISSUE TITLE
Error: 'NoneType' object has no attribute 'attributes'

### ISSUE THREAD

**Issue by chrys87** [valentinfrlch/ha-llmvision#177]
### Bug Description
I installed LLM Vision on my HA and created the automation using the blueprint. I get an Notification to my phone, but no description from the AI.
- AI Event Summary (LLM Vision v1.3.5)

- HA infromation: 
- Core -2025.1.2 
- Supervisor 2024.12.3 
- Operating System 14.1 
- Frontend 20250109.0 
- LLM Vision 1.3.6
- LLM Blueprint 1.3.5

complete trace: 
[trace automation.ai_event_summary_llm_vision_v1_3_5 2025-01-18T19_18_27.452726+00_00.json](https://github.com/user-attachments/files/18465813/trace.automation.ai_event_summary_llm_vision_v1_3_5.2025-01-18T19_18_27.452726%2B00_00.json)

### Service Call
```yaml
alias: AI Event Summary (LLM Vision v1.3.5)
description: ""
use_blueprint:
  path: valentinfrlch/event_summary.yaml
  input:
    mode: Camera
    notify_device:
      - 21d22beed9c1e6ee716b464bc2062afb
    preview_mode: Snapshot
    tap_navigate: "{{video if video != '''' else image}}"
    duration: 3
    max_frames: 1
    provider: 01JH6GF7XJ3H307SCNSSCY9SCK
    camera_entities:
      - camera.hausturkamera_mediaprofile_channel1_mainstream
    model: llava-phi3
    motion_sensors: []
    cooldown: 3

```

### Logs
```
Analyze event
Executed on: 18. Januar 2025 um 20:18:27
Error: 'NoneType' object has no attribute 'attributes'
Result:
choice: 1

this is the yaml of the analyze step what fails:

alias: Analyze event
choose:
  - conditions:
      - condition: template
        value_template: '{{ mode == ''Frigate'' }}'
    sequence:
      - action: llmvision.video_analyzer
        data:
          event_id: '{{ trigger.payload_json[''after''][''id''] }}'
          provider: 01JH6GF7XJ3H307SCNSSCY9SCK
          model: llava-phi3
          message: >-
            Summarize what's happening in the camera feed (one sentence max).
            Don't describe the scene! If there is a person, describe what
            they're doing and what they look like. If they look like a courier
            mention that! If nothing is happening, say so.
          remember: false
          generate_title: false
          include_filename: true
          max_frames: 1
          target_width: 1280
          detail: low
          max_tokens: 20
          temperature: 0.1
        response_variable: response
  - conditions:
      - condition: template
        value_template: '{{ mode == ''Camera'' }}'
    sequence:
      - action: llmvision.stream_analyzer
        data:
          image_entity: '{{[camera_entity]}}'
          duration: 3
          provider: 01JH6GF7XJ3H307SCNSSCY9SCK
          model: llava-phi3
          message: >-
            Summarize what's happening in the camera feed (one sentence max).
            Don't describe the scene! If there is a person, describe what
            they're doing and what they look like. If they look like a courier
            mention that! If nothing is happening, say so.
          remember: false
          generate_title: false
          include_filename: true
          max_frames: 1
          target_width: 1280
          detail: low
          max_tokens: 20
          temperature: 0.1
          expose_images: '{{true if preview_mode == ''Snapshot''}}'
        response_variable: response
```

### Additional context
when i try it in manually in "image_analyzer" everything seems to work. so my setup works at least.

**Comment by chrys87** [comment]
Here some debug information:

[home-assistant_llmvision_2025-01-18T22-29-03.354Z.log](https://github.com/user-attachments/files/18466387/home-assistant_llmvision_2025-01-18T22-29-03.354Z.log)

**Comment by valentinfrlch** [comment]
Thank you for including the trace and logs. What provider do you use?

**Comment by chrys87** [comment]
As AI Provider i use the offical ollama integration (i do not se an version number, so guess its the same like home assistant itsself)
the "server" binary is ollama version is 0.5.7 running on an most up to date arch linux.
I use this as well for the "Assist" speech home assistant voice assistant. there i get a response. so the infrastructure should work.
I testet several models but always the same result.

**Comment by chrys87** [comment]
Interesting is, using the developemnt tools everything works: 


```
action: llmvision.image_analyzer
data:
  include_filename: false
  target_width: 1280
  max_tokens: 100
  temperature: 0.2
  generate_title: false
  expose_images: false
  expose_images_persist: false
  provider: 01JH6GF7XJ3H307SCNSSCY9SCK
  model: llava-phi3:latest
  message: Beschreibe das Bild auf Deutsch!
  image_entity:
    - camera.hausturkamera_mediaprofile_channel1_mainstream
```
