### ISSUE TITLE
Truncation of Message - Developer Tools and App

### ISSUE THREAD

**Issue by loca5790** [valentinfrlch/ha-llmvision#182]
### Bug Description
Response is truncated to what appears to be a set number of characters.

**Version**:  1.3.6

### Service Call

Directly from blueprint
```  - alias: Analyze event
    choose:
      - conditions:
          - condition: template
            value_template: "{{ mode == 'Frigate' }}"
        sequence:
          - action: llmvision.video_analyzer
            data:
              event_id: "{{ trigger.payload_json['after']['id'] }}"
              provider: 
              model: llava-phi3
              message: >-
                Summarize what's happening in the camera feed (one sentence
                max). Don't describe the scene! If there is a person, describe
                what they're doing and what they look like. If they look like a
                courier mention that! If nothing is happening, say so.
              remember: true
              generate_title: true
              include_filename: true
              max_frames: 3
              target_width: 1280
              detail: low
              max_tokens: 20
              temperature: 0.1
            response_variable: response
```

Recreated in developer tools
```
action: llmvision.image_analyzer
metadata: {}
data:
  remember: false
  include_filename: false
  target_width: 1280
  max_tokens: 3000
  temperature: 0.2
  generate_title: true
  expose_images: false
  expose_images_persist: false
  provider: 
  model: llava-phi3
  message: >-
    Summarize what's happening in the camera feed (one sentence max). Don't
    describe the scene! If there is a person, describe what they're doing
    and what they look like. If they look like a courier mention that! If
    nothing is happening, say so. Don't use emojis!
  image_file: /config/www/llmvision/front_door_person.jpg
response_variable: response
```
In this condition it will not post anything after the automation even when I created my own automation.  I was trying to write  system log even post notify to capture the response variable but it would not write it despite the trace showing complete.

### Logs

```
Paste relevant logs here
```

### Additional context
Please see above.  The response is being tructated when a title is being generated.  Adding delays does not change it. Even on manual snapshot events it will force truncation of responses.

Does not fix frigate 404 issue.  I can access the same link via my local network will try adding longer delay.
