### ISSUE TITLE
Automation not trigger since the new Blueprint 1.3.7

### ISSUE THREAD

**Issue by Frazou1** [valentinfrlch/ha-llmvision#185]
### Bug Description

Since update the blueprint to 1.3.7 nothing trigger the automation, but if i look into frigate, i got event

**Version**: 1.3.7

### Service Call

```yaml
alias: Notif AI Cam Sonette
description: ""
use_blueprint:
  path: valentinfrlch/event_summary.yaml
  input:
    mode: Frigate
    notify_device:
      - d0d9e52e51bf00ca693a6161e29b1b6a
    camera_entities:
      - camera.cam_sonette
    required_zones:
      - cam sonette motion
    object_type:
      - person
      - car
    tap_navigate: "{{video if video != '''' else image}}"
    provider: 01JHNP36WMNRXSF2WYRTKT704X
    temperature: 0.3

```

### Logs

```
Paste relevant logs here
```

**Comment by jdfrench** [comment]
Same issue. My old notifications based on the SgtBatten blueprint work fine. Doesn't make much sense given that they both fire on frigate/events

**Comment by Lemonhead-Snickers** [comment]
> Could someone with this issue post traces?

I would love to, but I just installed two days ago and I've only run the new blueprint. As a result, my automation has _never_ triggered. See below that the SgtBatten blueprint has triggered, and I'll post the trace for that.

[trace automation.frigate_notifications_0_12_0_4c 2025-01-27T22_09_09.569034+00_00.json](https://github.com/user-attachments/files/18573972/trace.automation.frigate_notifications_0_12_0_4c.2025-01-27T22_09_09.569034%2B00_00.json)

![Image](https://github.com/user-attachments/assets/7c1e17a7-a1c6-440f-9829-cd6d214c4736)

**Comment by valentinfrlch** [comment]
The issue is likely the updated frigate trigger:

```yaml
trigger: mqtt
topic: frigate/events
id: frigate_trigger
enabled: "{{mode == 'Frigate'}}"
```
The `enabled` template should evaluate to true only if `mode` is set to "Frigate". Previously there was an issue that would throw an error if mqtt wasn't installed even though camera mode doesn't need mqtt.

**Comment by Frazou1** [comment]
Same thing here, i cant have trace because they never run. If you want to try something i can !

**Comment by popler** [comment]
+1

**Comment by Lemonhead-Snickers** [comment]
> The issue is likely the updated frigate trigger:
> 
> trigger: mqtt
> topic: frigate/events
> id: frigate_trigger
> enabled: "{{mode == 'Frigate'}}"
> The `enabled` template should evaluate to true only if `mode` is set to "Frigate". Previously there was an issue that would throw an error if mqtt wasn't installed even though camera mode doesn't need mqtt.

I may troubleshoot based on this a bit. 

Did the MQTT payload trigger change in this version 1.3.7? It looks like SgtBatten listens for the event type "new," while LLM Vision listens for the event type "end." Wondering if that could be the issue. Will try that too.

**Comment by Lemonhead-Snickers** [comment]
Sorry to keep updating, but could it be that "mode:" as a blueprint input variable is conflicting with HomeAssistant's "mode:" setting?

**Comment by airbornetrooper82573** [comment]
> Im not sure how i can do, but can we test a basic automation without the blueprint to see if is working ?

You can do that under developer tools > actions 
https://llm-vision.gitbook.io/examples/examples/scripts

**Comment by Lemonhead-Snickers** [comment]
> The issue is likely the updated frigate trigger:
> 
> trigger: mqtt
> topic: frigate/events
> id: frigate_trigger
> enabled: "{{mode == 'Frigate'}}"
> The `enabled` template should evaluate to true only if `mode` is set to "Frigate". Previously there was an issue that would throw an error if mqtt wasn't installed even though camera mode doesn't need mqtt.

Confirmed, in part. By removing any condition based on `mode == 'Frigate'`, the automation fires and listens on frigate/events. Note that line 306 in the blueprint sets `mode: single`, which probably conflicts. However, I've broken it somehow in my config because the trace is failing at the value template when I go walk in front of the camera. Not sure what's going on there, but will investigate more as I have time.

Here's what I changed it to:
```yaml
trigger:
  - platform: mqtt
    topic: frigate/events
    id: frigate_trigger
  - platform: state
    entity_id: !input camera_entities
    to: !input trigger_state
    id: camera_trigger
  - platform: state
    entity_id: !input motion_sensors
    to: "on"
    id: motion_sensor_trigger
condition:
  - condition: template
    value_template: >
      {{ trigger.payload_json["type"] == "new"
        and ('camera.' + trigger.payload_json['after']['camera']|lower) in camera_entities_list
        and ((object_types_list|length) == 0 or ((trigger.payload_json['after']['label']|lower) in object_types_list))
        and (not required_zones_list or ((set(trigger.payload_json['after']['current_zones']).intersection(required_zones_list))))
        and not (ignore_stationary and trigger.payload_json['after']['stationary'])
      }}
```
