### ISSUE TITLE
The model is overloaded. Please try again later.

### ISSUE THREAD

**Issue by wwelles** [valentinfrlch/ha-llmvision#188]
### Bug Description
Trying the action and Google Gemini I get the follow error log:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:820
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:43:59 AM (11 occurrences)
Last logged: 10:03:11 AM

[140532075134064] The model is overloaded. Please try again later.
[140531312393040] The model is overloaded. Please try again later.
```

**Version**: 1.3.8

### Service Call

```
action: llmvision.image_analyzer
data:
  provider: 01JKBFPDM3BGC2HBZKE45R08S0
  message: Describe the image in one sentence
  image_entity:
    - camera.laneway
  include_filename: true
  target_width: 1280
  max_tokens: 100
  temperature: 0.2
```
