### ISSUE TITLE
Blueprint Beta 1.4.0 tap to navigate doesnt work

### ISSUE THREAD

**Issue by Frazou1** [valentinfrlch/ha-llmvision#233]
### Description

Im trying to get the clip from frigate when i configure the tap to navigate option in the new blueprint but doesnt work.

**Version**: 1.4.0 

### Action Call

```yaml

alias: NOTIF AI Cam Sonette motion 1.4.0
description: ""
use_blueprint:
  path: valentinfrlch/event_summary_beta.yaml
  input:
    message: >-
      Résume ce qui se passe dans  la caméra (une phrase maximum). Ne décrit pas
      la scène ! S'il y a une personne, décrit ce qu'elle fait et à quoi elle
      ressemble. S'ils ressemblent à un livreur, mentionne-le. S'il y a un chien
      décris le.
    notify_device:
      - d0d9e52e51bf00ca693a6161e29b1b6a
    notification_delivery: Consolidated
    camera_entities:
      - camera.cam_sonette
    model: gemini-1.5-flash
    provider: 01JKS3YH3C8QV14ZKDKNSMCR2C
    tap_navigate: "{{action_url}}/api/events/{{id}}/clip.mp4"
    run_conditions:
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.cam_sonette_motion_dog_occupancy
            state: "on"
          - condition: state
            entity_id: binary_sensor.cam_sonette_motion_person_occupancy
            state: "on"
          - condition: state
            entity_id: binary_sensor.cam_sonette_motion_cat_occupancy
            state: "on"
    motion_sensors:
      - binary_sensor.cam_sonette_motion_all_occupancy
    temperature: 0.1
    max_tokens: 50
    preview_mode: Snapshot


```

### Logs

```

they bring me to a empty url

```

### Reproduction steps

1.
2.
3.
...
