### ISSUE TITLE
Beta 2 automation is erroring out

### ISSUE THREAD

**Issue by mayberryjp** [valentinfrlch/ha-llmvision#235]
worked on beta1 but now beta2 is erroring. didn't find anything in the updated docs or breaking fixes that seemed a match. i've since changed the automation to include use_memory: true,, but it hasn't triggered yet - wondering if no use_memory parameter was causing the error

```
action: llmvision.image_analyzer
metadata: {}
data:
  remember: true
  include_filename: true
  target_width: 1280
  max_tokens: 50
  model: gpt-4o
  temperature: 1
  generate_title: true
  expose_images: true
  expose_images_persist: true
  provider: 01JM72Z86ZZE8NJY01TS2VKATZ
  message: >-
    Summarize what is happening in the camera feed (one sentence max). Do not
    describe the scene! If there is an animal in the photo please describe the
    size, color and type of animal. If there is not an animal in the photo then
    simply state that no animal was detected. Make it humorous and
    condescending. Please also mention that the image is from camera
    {{trigger.payload_json["after"]["camera"]}}. 
  image_file: /config/previews/cat-{{trigger.payload_json["after"]["id"]}}.jpg
response_variable: llmvision_response
```

logs

2025-02-27 23:14:58.167 ERROR (MainThread) [homeassistant.components.automation.motion_cat_record_event] MOTION | CAT | RECORD EVENT: Error executing script. Unexpected error for call_service at pos 3: 'NoneType' object has no attribute 'data'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 762, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2794, in async_call
    response_data = await coro
  File "/usr/src/homeassistant/homeassistant/core.py", line 2837, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/llmvision/__init__.py", line 395, in image_analyzer
    call.memory = Memory(hass)
                  ~~~~~~^^^^^^
  File "/config/custom_components/llmvision/memory.py", line 25, in __init__
    self._system_prompt = system_prompt if system_prompt else self.entry.data.get(
                                                              ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
2025-02-27 23:14:58.171 ERROR (MainThread) [homeassistant.components.automation.motion_cat_record_event] While executing automation automation.motion_cat_record_event
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 717, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        variables, trigger_context, started_action
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1808, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
    ~~~~~~~~~~~~~~~~~~~~~~^
        ex, continue_on_error, self._log_exceptions or log_exceptions
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 558, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 762, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task

           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2794, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2837, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/llmvision/__init__.py", line 395, in image_analyzer
    call.memory = Memory(hass)
                  ~~~~~~^^^^^^
  File "/config/custom_components/llmvision/memory.py", line 25, in __init__
    self._system_prompt = system_prompt if system_prompt else self.entry.data.get(
                                                              ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
