### ISSUE TITLE
[Add FEATURE] Mistral AI

### ISSUE THREAD

**Issue by maartenhendrix** [valentinfrlch/ha-llmvision#259]
**Is your feature request related to a problem? Please describe.**
No problem 

**Describe the solution you'd like**

As a user I would like to be able to use Mistral AI with LLM Vision. 

**Documentation**
https://docs.mistral.ai/api/

**Comment by JacquesBe35** [comment]
Use custom endpoint in llmvision and use mistral endpoint. 
Model : pixtral-12b-latest
Working fine for me

**Comment by maartenhendrix** [comment]
that works. thank you!

**Comment by ronaldt80** [comment]
Following the changes to Gemini I want to use LLM Vision with Mistral AI but so far little luck; when testing the model in developer options I get the following error:

`Provider Custom OpenAI failed: {'detail': [{'type': 'extra_forbidden', 'loc': ['body', 'max_completion_tokens'], 'msg': 'Extra inputs are not permitted', 'input': 3000}]}`

I already tried to turn off the options but it seems to send the max completion tokens as a default; any one with more luck?


Action settings:
```
action: llmvision.image_analyzer
data:
  message: Describe the image
  provider: 01KDJQNMR7GCPVNVARKCPESFT4
  include_filename: true
  image_entity:
    - camera.doorbell_unifi
```

I use the following end point: `https://api.mistral.ai/v1/chat/completions` with default model `pixtral-12b-latest`
