### ISSUE TITLE
Cannot create automation from blueprint v1.4.1: "Message malformed: extra keys not allowed @ data['triggers']"

### ISSUE THREAD

**Issue by vdiogo** [valentinfrlch/ha-llmvision#284]
### Checklist

- [x] I'm running the newest version of LLM Vision <https://github.com/valentinfrlch/ha-llmvision/releases/latest>
- [x] I have enabled debug logging for the integration.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This is a bug and not a feature request.
- [x] I have searched [open issues](https://github.com/valentinfrlch/ha-llmvision/issues) for my problem.

### Describe the issue

I had an older version of the blueprint and updated/ downloaded the latest one, so had to redo the automation as the previous stopped working.

Upon trying to create an automation from scratch, I get a "Message malformed: extra keys not allowed @ data['triggers']" error.

This is my yaml:
```
description: ""
alias: AI Event Summary (v1.4.1) - Ollama
use_blueprint:
  path: valentinfrlch/event_summary.yaml
  input:
    notify_device:
      - 1b50022586d1cce3b7e80efd3966ffb7
    provider: 01JPF7TXBK3M230GXRFXYC4ZR1
    model: minicpm-v:latest

```

Do I need to fill in other fields? I have tried multiple options: filling in a specific camera, including a trigger, ... but none seemed to work

### Reproduction steps

1. Download new blueprint
2. Create automation from blueprint
3. Add model + notification target
...

### Debug logs

```text
Not available (or at least don't know how to get them)
```

**Comment by valentinfrlch** [comment]
You need to fill all fields except `motion_sensors`. The problem is likely an old field that no longer exists. To fix this you could create a new automation from the blueprint (instead of modifying the old one) or edit the automation in yaml mode and remove the field(s) that no longer exist.

**Comment by vdiogo** [comment]
> You need to fill all fields except `motion_sensors`. The problem is likely an old field that no longer exists. To fix this you could create a new automation from the blueprint (instead of modifying the old one) or edit the automation in yaml mode and remove the field(s) that no longer exist.

I am creating an automation from the blueprint. This time with a camera:

<img width="434" alt="Image" src="https://github.com/user-attachments/assets/92c52862-ec26-46ff-b326-ac5a6c1f1384" />

**Comment by valentinfrlch** [comment]
Ok, but there are lots of input fields missing. See the setup guide here: https://llm-vision.gitbook.io/getting-started/setup/blueprint

**Comment by vdiogo** [comment]
> Ok, but there are lots of input fields missing. See the setup guide here: https://llm-vision.gitbook.io/getting-started/setup/blueprint

Sorry, I did filled everything that was mandatory and added some which was optional, but still getting same error

<img width="447" alt="Image" src="https://github.com/user-attachments/assets/cd30bb62-0bfc-40ac-bdb7-ee13a1b2b27f" />

**Comment by valentinfrlch** [comment]
`notify_device` and a lot of other input fields are still missing. I suggest editing the blueprint in the UI (instead of yaml). It's easier to see all fields.


Example configuration:
```yaml
alias: Blueprint
description: ""
use_blueprint:
  path: valentinfrlch/event_summary.yaml
  input:
    provider: provider id
    camera_entities:
      - camera.example
    cooldown: 3
    temperature: 0.3
    max_tokens: 70
    motion_sensors:
      - binary_sensor.example
    remember: true
    notify_device:
      - phone_id
    run_conditions: []
    max_frames: 2
    duration: 5
    model: model
    target_width: 1280
    message: >-
      prompt
```
