### ISSUE TITLE
Failed to call service gpt4vision.image_analyzer. None

### ISSUE THREAD

**Issue by sshaikh** [valentinfrlch/ha-llmvision#35]
**Describe the bug**

I am unable to make calls to Local AI. The same service call to Open AI (albeit with a different model) works correctly.

**To Reproduce**
1. Use the GUI to set up a service call:
```
service: gpt4vision.image_analyzer
data:
  provider: LocalAI
  max_tokens: 100
  model: gpt-4-vision-preview #also tried gpt-4. With OpenAI, use gpt-4o
  image_entity:
    - camera.driveway
  target_width: 1280
  detail: low
  temperature: 0.5
  include_filename: false
  message: Describe what you see?
```
2. See failure

**Version**
- [x] I am on the latest version

**Expected behavior**
Receive a description of the image as in the OpenAI call.

**Logs**
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:2005
First occurred: 17:16:15 (3 occurrences)
Last logged: 17:17:12

websocket_api script: Error executing script. Error for call_service at pos 1: None
```
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:797
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:16:15 (3 occurrences)
Last logged: 17:17:12

[138509790739136] None
```
and on localai:
```
local-ai  | 4:17PM WRN Client error ip=172.29.0.1 latency="151.755µs" method=GET status=404 url=/v1/chat/completions
```

**Additional context**
The `curl` test as advised by localAI works:

```
$ curl https://localai-server:1443/v1/chat/completions -H "Content-Type: application/json" -d '{ "model": "gpt-4-vision-preview", "messages": [{"role":"user", "content": [{"type":"text", "text": "What is in the image?"},{"type": "image_url", "image_url": {"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg" }}], "temperature": 0.9}]}'
{"created":1721680908,"object":"chat.completion","id":"98435afb-11f2-48d7-9e74-7c83e3ba8712","model":"gpt-4-vision-preview","choices":[{"index":0,"finish_reason":"stop","message":{"role":"assistant","content":"The image features a wooden walkway or bridge that is surrounded by tall grass or a field of flowers.\u003c/s\u003e"}}],"usage":{"prompt_tokens":1,"completion_tokens":22,"total_tokens":23}}
```

**Comment by valentinfrlch** [comment]
Thank you for including the curl request. Honestly I haven't tested LocalAI in a while and was planning to remove it (because Ollama is both easier to install and faster - at least for me).

The error code (404) you get is typically returned when the model is not found. However since curl works I don't think that is the problem. I'll check asap but I need to set up LocalAI again.

**Comment by sshaikh** [comment]
Thanks - if I'm the only one using LocalAI then happy to switch it out to Ollama :D. Thought the former was becoming the defacto standard.

**Comment by valentinfrlch** [comment]
No, I'm happy to support LocalAI as long as people are using it. I'll look into it.

**Comment by valentinfrlch** [comment]
So got LocalAI running again and tested it with the following service call:
```
service: gpt4vision.image_analyzer
data:
  provider: LocalAI
  max_tokens: 100
  temperature: 0.5
  image_entity:
    - camera.front_door
  message: Describe the image
```
Which worked. I have also tested it with the exact same service call you had above and it worked too.
How did you set up LocalAI? I am running the cuda-12 compatible docker image.
You might want to reinstall LocalAI and make sure it downloads the model correctly.
