### ISSUE TITLE
Failed to call service llmvision.video_analyzer. None

### ISSUE THREAD

**Issue by darkneo29** [valentinfrlch/ha-llmvision#43]
**Describe the bug**
When calling the service LLM Vision: Video Analyzer and using Google as the provider I get this error Failed to call service llmvision.video_analyzer. None.  When I use OPENAI it works

**Version**
1.0.1

**Logs**
```
Paste relevant logs here
Maybe this??
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:2002
First occurred: 9:38:18 AM (9 occurrences)
Last logged: 9:55:04 AM

websocket_api script: Error executing script. Error for call_service at pos 1: None

**Comment by valentinfrlch** [comment]
What did you use as model? You can leave the parameter blank to use the default model for the selected provider. 
There is a known bug right now that will throw this error instead of properly stating that the model doesn't exist.

Let me know if that works.

**Comment by darkneo29** [comment]
Hey,
I am using gemini-1.5-flash and Pro and error on both but when I try via image it works with though models.. I tried blank as well and no luck same error

**Comment by valentinfrlch** [comment]
Can you please provide the service call so I can reproduce the error?
This works for me:
```yaml
service: llmvision.image_analyzer
data:
  provider: Google
  include_filename: true
  target_width: 1280
  max_tokens: 100
  temperature: 0.5
  message: Describe the image
  image_entity:
    - camera.entity
  detail: high
```

**Comment by darkneo29** [comment]
service: llmvision.video_analyzer
data:
  provider: Google
  model: gemini-1.5-flash
  interval: 3
  target_width: 1280
  detail: high
  max_tokens: 300
  temperature: 0.5
  video_file: /config/www/snapshots/vidgarage.mp4
  message: >-
    Review this video Clip. You are a security guard reviewing the garage camera
    video, your job is to keep the home safe and let us know if any suspicious
    activity is detected. Keep your response short and too the point. At the end
    of your response type either threat=detected or threat=safe
  include_filename: true
response_variable: response

**Comment by darkneo29** [comment]
The image works fine. It's the new video part that doesn't work when I select Google. When I select OpenAI, there are no issues. When I use the image function, everything works for Google as well.

**Comment by valentinfrlch** [comment]
I cannot reproduce the error. This works:
```yaml
service: llmvision.video_analyzer
data:
  provider: Google
  model: gemini-1.5-flash
  interval: 5
  target_width: 1280
  detail: high
  max_tokens: 300
  temperature: 0.5
  video_file: /config/www/tmp/test.mp4
  message: >-
    Review this video Clip. You are a security guard reviewing the garage camera
    video, your job is to keep the home safe and let us know if any suspicious
    activity is detected. Keep your response short and too the point. At the end
    of your response type either threat=detected or threat=safe
  include_filename: true
```

response:
```
response_text: >
  The man in the video appears to be a resident of the home. He is carrying
  groceries and appears to be entering the home. 

  threat=safe 
```

The only way I get the `None` error is, if I leave the model parameter blank which Home Assistant then automatically sets to `null`. This won't work:
```yaml
...
model: null
model:
...
```

Either set the parameter to an existing model or leave the parameter out.

If the issue persists I need more logs as otherwise there is no way for me to understand what's going on.
You can enable debug logging by adding this to your `configuration.yaml`:
```yaml
logger:
  logs:
    custom_components.llmvision: debug
```
