### ISSUE TITLE
This service requires field provider, which must be provided under data

### ISSUE THREAD

**Issue by Tokn59** [valentinfrlch/ha-llmvision#47]
### Bug Description

**Version**: 

### Service Call

```yaml
service: llmvision.image_analyzer
data:
  model: gpt-4o-mini
  message: Describe the person present in the photo
  image_file: /config/www/images/tony.jpg
  target_width: 1280
  max_tokens: 100
  temperature: 0.5
```

### Logs

```
Paste relevant logs here
```

### Additional context

U_I can't seem to find a "field" provider .. What al I missing ?
btw ... I'm on Free Tier and have 18$ limit open.

**Comment by valentinfrlch** [comment]
Please refer to the README where a sample service call is given. You are missing the `provider` key
Your service call should look like this:
```yaml
service: llmvision.image_analyzer
data:
  provider: OpenAI
  model: gpt-4o-mini
  message: Describe the person present in the photo
  image_file: /config/www/images/tony.jpg
  target_width: 1280
  max_tokens: 100
  temperature: 0.5
```
