### ISSUE TITLE
use question! `responce_variable`

### ISSUE THREAD

**Issue by Anto79-ops** [valentinfrlch/ha-llmvision#55]
Thanks for your integration!

I don't have an issue but couldn't find a discussion section so I would like to post here.

I'm currently using google AI for image analysis of photos generated by a camera. For example:

```
  - data:
      image_filename: www/bird_feeder/blink_camera_still_image.jpg
      prompt: >-
        Name the type of bird in the photo. Do NOT use special characters in
        your responce like asterisks *
    response_variable: generated_content
    action: google_generative_ai_conversation.generate_content
```

But when I try to use your service/action call with Ollama local, it works excpets it does not like to use the `responce_variable`

```
  - action: llmvision.image_analyzer
    data:
      provider: Ollama
      target_width: 1280
      detail: high
      max_tokens: 100
      temperature: 0.5
      model: llava:34b-v1.6-q8_0
      message: >-
        Name the type of bird in the photo. If there is no bird, say there is no
        bird. Do NOT use special characters in your responce like asterisks *
      image_file: www/bird_feeder/blink_camera_still_image.jpg
      response_variable: generated_content
```

I don't know if im doing something wrong or if its not supported? 

thanks for your help
