### ISSUE TITLE
llmvision.stream_analyzer. No image input provided

### ISSUE THREAD

**Issue by Ganfoud** [valentinfrlch/ha-llmvision#74]
### Bug Description

When testing the action on a stream in the developper tools, I get the error "llmvision.stream_analyzer. No image input provided"

**Version**: 1.2.1

### Service Call

```yaml
action: llmvision.stream_analyzer
data:
  include_filename: true
  target_width: 1280
  detail: low
  max_tokens: 100
  temperature: 0.2
  provider: 01JAT1BF7V5DTWSHBQ2T2F7EXT
  image_entity:
    - camera.camera_interieure_rdc
  duration: 10
  message: "Describe what happens in the camera feed "

```

### Logs

```
Paste relevant logs here
```
