### ISSUE TITLE
Validation error: Request failed:

### ISSUE THREAD

**Issue by Innominatapersona** [valentinfrlch/ha-llmvision#98]
### Bug Description

Getting no response from Ollama 

### Version
**v1.3.1**: 

### Service Call

```
action: llmvision.image_analyzer
data:
  provider: 01JCAD4PWZ5N3C69Q954SCVJW3
  model: llava-phi3
  message: Tell me the name of the object you see in the image. Use just one word. Don't add any other word to your answer.
  image_entity:
    - camera.ipc_01_profile_000
  detail: low
  target_width: 1280
  include_filename: true
  max_tokens: 100
  temperature: 0.2
```

### Logs

_Probably this one (?)_

```
Registratore: homeassistant.components.websocket_api.http.connection
Fonte: components/websocket_api/commands.py:287
Integrazione: Home Assistant WebSocket API (documentazione, problemi)
Prima occorrenza: 20:21:29 (1 occorrenze)
Ultima registrazione: 20:21:29

[548062536048] Request failed:
```

### Additional context

**Home assistant installation:**
- Home Assistant OS supervised on RPI5
- Core 2024.11.2
- Supervisor 2024.11.4
- Operating System 13.2
- Frontend 20241106.2
- LAN connection to router

**Ollama installation:**
- Amd64 PC running Ubuntu server 24.04
- Model: llava-phi3 
- LAN connection to router

**Behaviours:**
- Camera entity works well.
- Ollama server works well performing as assist conversation agent (no control, only assist), so server is exposed and can receive intents and give responses back to home assistant.
- Ollama llava-phi3 model on Ubuntu server terminal is capable of analyzing images stored on internal storage and give text responses.
- Those text responses are quite slow to be typed.
- The command "Ollama ps" on ubuntu server terminal after calling Home assistant service reveals the model is running, so the call seems to be received and the model seems to be working to analyze the image.
```
ai@ai:~$ ollama ps
NAME                 ID              SIZE     PROCESSOR    UNTIL              
llava-phi3:latest    c7edd7b87593    10 GB    100% CPU     4 minutes from now 
```
- the script runs for 5 minutes (300.** seconds) before giving the error, _which seems a reasonable time for everyone to stop waiting for an answer._

**Other probably useful informations:**
- The model has been asked to identify the object displayed on camera (scissors placed on a clear wall background) using just one word and not to add any other word to the answer. This should exclude the chance that the time of typing exceeds the expected answer time, but that's only a guess.
- config.yaml is split off and some of the entries are commented. Uncommenting all of them one by one made no difference. If there are necessary system integrations required to run at the base, they could maybe be missing.

### ____________________

Hi,
really love what you did and sorry, I've been trying for 2 weeks to make this work, but: no way. 
Some of the informations I collected seem to point to slow system performances, but since local Ollama analysis is fast and the answer I ask is also fast to type, I thought there could be something I was missing. Before stepping to new hardware crysis, I'd like to make sure I wasn't.
So, if you could share any piece of advice, I'd really appreciate it.
Thank you very much for your patience and help.
